# Generated by Django 4.2.9 on 2024-02-09 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_messages_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='unique_relationship_inverse',
        ),
        migrations.AlterField(
            model_name='messages',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 9, 14, 1, 28, 979925)),
        ),
    ]
